### ISSUE TITLE
Confused 

### ISSUE THREAD

**Issue by jjpe** [andrewmcwatters/include.js#1]
Hi there! 

This is not a troll post, I'm genuinely confused by this. How is this different from an iframe?

**Comment by andrewmcwatters** [comment]
Hello!

An [`iframe`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) has its own specific browsing context and separate `Document`. In cases where you'd simply like to include a document fragment into your current active document, include.js is a better solution.

Its design is inspired by AngularJS's [`ngInclude`](https://docs.angularjs.org/api/ng/directive/ngInclude).

**Comment by jjpe** [comment]
Yes it does! Thank you, also for answering so quickly.
